id: I3110F429
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-04-05T05:18:49+00:00'
last_modified: '2022-06-16T05:20:40.081843+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4582
  title: ཨར་བྱང་ཆུབ་ཡེ་ཤེས་ཀྱི་གསུང་ཆོས་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    875B:
      image_group_id: I1GS88132
      title: ''
      total_pages: ''
      order: 1
      base_file: 875B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
